// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/alert.proto

package alert

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Condition for price alerts
type AlertCondition int32

const (
	AlertCondition_CONDITION_UNSPECIFIED AlertCondition = 0
	AlertCondition_ABOVE                 AlertCondition = 1
	AlertCondition_BELOW                 AlertCondition = 2
)

// Enum value maps for AlertCondition.
var (
	AlertCondition_name = map[int32]string{
		0: "CONDITION_UNSPECIFIED",
		1: "ABOVE",
		2: "BELOW",
	}
	AlertCondition_value = map[string]int32{
		"CONDITION_UNSPECIFIED": 0,
		"ABOVE":                 1,
		"BELOW":                 2,
	}
)

func (x AlertCondition) Enum() *AlertCondition {
	p := new(AlertCondition)
	*p = x
	return p
}

func (x AlertCondition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertCondition) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_alert_proto_enumTypes[0].Descriptor()
}

func (AlertCondition) Type() protoreflect.EnumType {
	return &file_proto_alert_proto_enumTypes[0]
}

func (x AlertCondition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertCondition.Descriptor instead.
func (AlertCondition) EnumDescriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{0}
}

// CreateAlertRequest is the request message for creating a new alert.
type CreateAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`                                  // Stock symbol, e.g., "AAPL"
	TargetPrice   float64                `protobuf:"fixed64,3,opt,name=target_price,json=targetPrice,proto3" json:"target_price,omitempty"`   // Target price to trigger alert
	Condition     AlertCondition         `protobuf:"varint,4,opt,name=condition,proto3,enum=alert.AlertCondition" json:"condition,omitempty"` // ABOVE or BELOW
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertRequest) Reset() {
	*x = CreateAlertRequest{}
	mi := &file_proto_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertRequest) ProtoMessage() {}

func (x *CreateAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertRequest.ProtoReflect.Descriptor instead.
func (*CreateAlertRequest) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAlertRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateAlertRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CreateAlertRequest) GetTargetPrice() float64 {
	if x != nil {
		return x.TargetPrice
	}
	return 0
}

func (x *CreateAlertRequest) GetCondition() AlertCondition {
	if x != nil {
		return x.Condition
	}
	return AlertCondition_CONDITION_UNSPECIFIED
}

// CreateAlertResponse is the response message after creating an alert.
type CreateAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertId       int32                  `protobuf:"varint,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertResponse) Reset() {
	*x = CreateAlertResponse{}
	mi := &file_proto_alert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertResponse) ProtoMessage() {}

func (x *CreateAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertResponse.ProtoReflect.Descriptor instead.
func (*CreateAlertResponse) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAlertResponse) GetAlertId() int32 {
	if x != nil {
		return x.AlertId
	}
	return 0
}

func (x *CreateAlertResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetAlertsRequest is the request message for retrieving alerts.
type GetAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // Filter by user (0 = all users)
	ActiveOnly    bool                   `protobuf:"varint,2,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"` // Only return non-triggered alerts
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertsRequest) Reset() {
	*x = GetAlertsRequest{}
	mi := &file_proto_alert_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertsRequest) ProtoMessage() {}

func (x *GetAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertsRequest.ProtoReflect.Descriptor instead.
func (*GetAlertsRequest) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{2}
}

func (x *GetAlertsRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetAlertsRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

// Alert represents a single alert entry.
type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	TargetPrice   float64                `protobuf:"fixed64,4,opt,name=target_price,json=targetPrice,proto3" json:"target_price,omitempty"`
	Condition     AlertCondition         `protobuf:"varint,5,opt,name=condition,proto3,enum=alert.AlertCondition" json:"condition,omitempty"`
	Triggered     bool                   `protobuf:"varint,6,opt,name=triggered,proto3" json:"triggered,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_proto_alert_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{3}
}

func (x *Alert) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Alert) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Alert) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Alert) GetTargetPrice() float64 {
	if x != nil {
		return x.TargetPrice
	}
	return 0
}

func (x *Alert) GetCondition() AlertCondition {
	if x != nil {
		return x.Condition
	}
	return AlertCondition_CONDITION_UNSPECIFIED
}

func (x *Alert) GetTriggered() bool {
	if x != nil {
		return x.Triggered
	}
	return false
}

func (x *Alert) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// GetAlertsResponse is the response message containing a list of alerts.
type GetAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertsResponse) Reset() {
	*x = GetAlertsResponse{}
	mi := &file_proto_alert_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertsResponse) ProtoMessage() {}

func (x *GetAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertsResponse.ProtoReflect.Descriptor instead.
func (*GetAlertsResponse) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{4}
}

func (x *GetAlertsResponse) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

var File_proto_alert_proto protoreflect.FileDescriptor

const file_proto_alert_proto_rawDesc = "" +
	"\n" +
	"\x11proto/alert.proto\x12\x05alert\"\x9d\x01\n" +
	"\x12CreateAlertRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12!\n" +
	"\ftarget_price\x18\x03 \x01(\x01R\vtargetPrice\x123\n" +
	"\tcondition\x18\x04 \x01(\x0e2\x15.alert.AlertConditionR\tcondition\"J\n" +
	"\x13CreateAlertResponse\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\x05R\aalertId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"L\n" +
	"\x10GetAlertsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1f\n" +
	"\vactive_only\x18\x02 \x01(\bR\n" +
	"activeOnly\"\xdd\x01\n" +
	"\x05Alert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12!\n" +
	"\ftarget_price\x18\x04 \x01(\x01R\vtargetPrice\x123\n" +
	"\tcondition\x18\x05 \x01(\x0e2\x15.alert.AlertConditionR\tcondition\x12\x1c\n" +
	"\ttriggered\x18\x06 \x01(\bR\ttriggered\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"9\n" +
	"\x11GetAlertsResponse\x12$\n" +
	"\x06alerts\x18\x01 \x03(\v2\f.alert.AlertR\x06alerts*A\n" +
	"\x0eAlertCondition\x12\x19\n" +
	"\x15CONDITION_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05ABOVE\x10\x01\x12\t\n" +
	"\x05BELOW\x10\x022\x94\x01\n" +
	"\fAlertService\x12D\n" +
	"\vCreateAlert\x12\x19.alert.CreateAlertRequest\x1a\x1a.alert.CreateAlertResponse\x12>\n" +
	"\tGetAlerts\x12\x17.alert.GetAlertsRequest\x1a\x18.alert.GetAlertsResponseB*Z(github.com/tiongMax/gostocks/proto/alertb\x06proto3"

var (
	file_proto_alert_proto_rawDescOnce sync.Once
	file_proto_alert_proto_rawDescData []byte
)

func file_proto_alert_proto_rawDescGZIP() []byte {
	file_proto_alert_proto_rawDescOnce.Do(func() {
		file_proto_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_alert_proto_rawDesc), len(file_proto_alert_proto_rawDesc)))
	})
	return file_proto_alert_proto_rawDescData
}

var file_proto_alert_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_alert_proto_goTypes = []any{
	(AlertCondition)(0),         // 0: alert.AlertCondition
	(*CreateAlertRequest)(nil),  // 1: alert.CreateAlertRequest
	(*CreateAlertResponse)(nil), // 2: alert.CreateAlertResponse
	(*GetAlertsRequest)(nil),    // 3: alert.GetAlertsRequest
	(*Alert)(nil),               // 4: alert.Alert
	(*GetAlertsResponse)(nil),   // 5: alert.GetAlertsResponse
}
var file_proto_alert_proto_depIdxs = []int32{
	0, // 0: alert.CreateAlertRequest.condition:type_name -> alert.AlertCondition
	0, // 1: alert.Alert.condition:type_name -> alert.AlertCondition
	4, // 2: alert.GetAlertsResponse.alerts:type_name -> alert.Alert
	1, // 3: alert.AlertService.CreateAlert:input_type -> alert.CreateAlertRequest
	3, // 4: alert.AlertService.GetAlerts:input_type -> alert.GetAlertsRequest
	2, // 5: alert.AlertService.CreateAlert:output_type -> alert.CreateAlertResponse
	5, // 6: alert.AlertService.GetAlerts:output_type -> alert.GetAlertsResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_alert_proto_init() }
func file_proto_alert_proto_init() {
	if File_proto_alert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_alert_proto_rawDesc), len(file_proto_alert_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_alert_proto_goTypes,
		DependencyIndexes: file_proto_alert_proto_depIdxs,
		EnumInfos:         file_proto_alert_proto_enumTypes,
		MessageInfos:      file_proto_alert_proto_msgTypes,
	}.Build()
	File_proto_alert_proto = out.File
	file_proto_alert_proto_goTypes = nil
	file_proto_alert_proto_depIdxs = nil
}
